/**
 * Generates src/components/icons/icon-data.ts from the pinned
 * @iconify-json/hugeicons devDependency.
 *
 * The icon set is a devDependency on purpose: nothing from it reaches the
 * runtime bundle. Only the icons listed below are extracted, as static SVG
 * markup, so the public site ships no icon library and makes no CDN request.
 * See design.md §4.
 *
 * Re-run after adding an icon name:  node scripts/generate-icons.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";

// design.md §4 — the complete inventory used by the public site.
//
// Two artboard names do not exist in hugeicons and are substituted:
//   dog          -> horse    (veterinary/livestock; the copy itself says المواشي)
//   footprint-01 -> walking  ("arriving on foot")
// Verified against @iconify-json/hugeicons@1.2.33 — this script fails loudly
// rather than silently emitting a blank icon if a name goes missing again.
const NAMES = [
  "alarm-clock", "alert-02", "alert-circle", "alert-diamond", "apple",
  "app-store", "arrow-down-01", "baby-bottle",
  "bed", "building-03", "building-06", "calendar-03", "calendar-check-in-01",
  "call-02", "call-ringing-02", "cancel-01", "car-03", "car-04", "cleaning-bucket",
  "clock-01", "cloud-fast-wind", "compass", "dashboard-square-02", "delete-02",
  "delivery-truck-02", "filter", "fire", "flash", "horse",
  "gift", "github", "grid-view", "heart-check", "home-09", "house-01",
  "house-04", "kitchen-utensils", "layers-01", "layout-2-column",
  "link-square-02", "list-view", "location-01", "location-05",
  "location-user-02", "map-pinpoint-02", "maps",
  "maps-global-01", "maps-location-02", "medicine-02", "menu-01",
  "more-horizontal", "motorbike-02", "navigation-03", "news", "noodles", "package",
  "package-process", "play-store", "plus-sign", "police-badge", "pulse-02", "radio",
  "refresh", "road-01", "search-01", "sent", "shield-01", "shield-user",
  "shipping-truck-01", "square-arrow-expand-01", "stethoscope", "table-01",
  "t-shirt", "tent", "tree-06", "truck",
  "truck-delivery", "user-check-01", "user-group", "user-multiple", "walking",
  "water-energy", "workflow-square-10",
];

const set = JSON.parse(
  readFileSync("node_modules/@iconify-json/hugeicons/icons.json", "utf8"),
);

const resolve = (name) => {
  const alias = set.aliases?.[name];
  const icon = set.icons[name] ?? (alias ? set.icons[alias.parent] : undefined);
  return icon ? { ...icon, ...(alias ?? {}) } : undefined;
};

const missing = NAMES.filter((n) => !resolve(n));
if (missing.length) {
  console.error(`Not in @iconify-json/hugeicons:\n  ${missing.join("\n  ")}`);
  process.exit(1);
}

const entries = [...new Set(NAMES)].sort().map((name) => {
  const icon = resolve(name);
  const w = icon.width ?? set.width ?? 24;
  const h = icon.height ?? set.height ?? 24;
  return `  ${JSON.stringify(name)}: { vb: "0 0 ${w} ${h}", body: ${JSON.stringify(icon.body)} },`;
});

writeFileSync(
  "src/components/icons/icon-data.ts",
  `// GENERATED by scripts/generate-icons.mjs — do not edit.
// Source: @iconify-json/hugeicons (devDependency, pinned). design.md §4
export const iconData = {
${entries.join("\n")}
} as const;

export type IconName = keyof typeof iconData;
`,
);

console.log(`Wrote ${entries.length} icons to src/components/icons/icon-data.ts`);
